In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import numpy as np

In [2]:
data_root = '../energy_predict_data'  # 改成自己电脑上的路径即可
dataset = pd.read_csv(data_root + '/predict_data_e_train.csv')
header = dataset.columns.values.tolist()
dataset.head()

vehicle_id  charge_start_time  charge_end_time  mileage  charge_start_soc  \
0           1     20171101113839   20171101144639  69054.6              61.2   
1           1     20171101212850   20171102045945  69180.2              34.0   
2           1     20171102121246   20171102154916  69284.2              54.0   
3           1     20171102204546   20171103025825  69377.0              46.0   
4           1     20171103164054   20171103170824  69431.6              75.2   

   charge_end_soc  charge_start_U  charge_end_U  charge_start_I  charge_end_I  \
0            90.0           367.8         377.3            -7.7          -7.8   
1           100.0           363.4         400.6            -7.7          -7.7   
2            87.2           367.4         377.0            -7.7          -7.8   
3           100.0           366.6         399.0            -7.7          -7.8   
4            97.2           372.8         385.8           -29.9         -40.1   

   charge_max_temp  charge_min_temp  charge_energy  
0             21.0             16.0          9.071  
1             19.0             15.0         21.745  
2             23.0             17.0         10.434  
3             21.0             16.0         17.990  
4             18.0             15.0          6.990

In [3]:
testA = pd.read_csv(data_root +'/testA.csv')
testA_car = []
testA_car.append(testA[testA['vehicle_id']==1])
testA_car.append(testA[testA['vehicle_id']==2])
testA_car.append(testA[testA['vehicle_id']==3])
testA_car.append(testA[testA['vehicle_id']==4])
testA_car.append(testA[testA['vehicle_id']==5])
testA_car[2]

vehicle_id  charge_start_time  charge_end_time   mileage  \
7            3     20171201224526   20171201234816  142088.0   
8            3     20180123145343   20180123160544  150811.0   
9            3     20180304225122   20180305015229  155400.0   
10           3     20180519113736   20180519122556  169134.0   
11           3     20180610123152   20180610132701  172287.0   

    charge_start_soc  charge_end_soc  charge_start_U  charge_end_U  \
7                6.4            31.6           319.5         370.7   
8               11.2            34.4           330.5         371.5   
9               58.0            86.0           349.4         374.5   
10              82.0            90.0           365.6         372.6   
11              46.0            86.0           344.0         373.9   

    charge_start_I  charge_end_I  charge_max_temp  charge_min_temp  
7            -25.7         -16.2             27.0             10.0  
8            -84.2         -15.4             16.0              1.0  
9             -8.5          -7.9             14.0              6.0  
10            -8.1          -8.0             27.0             23.0  
11           -70.5         -16.3             34.0             24.0

In [4]:
dataset_car = []
dataset_car.append(dataset[dataset["vehicle_id"]==1])
dataset_car.append(dataset[dataset["vehicle_id"]==2])
dataset_car.append(dataset[dataset["vehicle_id"]==3])
dataset_car.append(dataset[dataset["vehicle_id"]==4])
dataset_car.append(dataset[dataset["vehicle_id"]==5])
dataset_car[0].head()

vehicle_id  charge_start_time  charge_end_time  mileage  charge_start_soc  \
0           1     20171101113839   20171101144639  69054.6              61.2   
1           1     20171101212850   20171102045945  69180.2              34.0   
2           1     20171102121246   20171102154916  69284.2              54.0   
3           1     20171102204546   20171103025825  69377.0              46.0   
4           1     20171103164054   20171103170824  69431.6              75.2   

   charge_end_soc  charge_start_U  charge_end_U  charge_start_I  charge_end_I  \
0            90.0           367.8         377.3            -7.7          -7.8   
1           100.0           363.4         400.6            -7.7          -7.7   
2            87.2           367.4         377.0            -7.7          -7.8   
3           100.0           366.6         399.0            -7.7          -7.8   
4            97.2           372.8         385.8           -29.9         -40.1   

   charge_max_temp  charge_min_temp  charge_energy  
0             21.0             16.0          9.071  
1             19.0             15.0         21.745  
2             23.0             17.0         10.434  
3             21.0             16.0         17.990  
4             18.0             15.0          6.990

In [5]:
from sklearn.cluster import KMeans
perfect_data = pd.read_csv(data_root + '/perfect.csv')
# 获取列名
header = perfect_data.columns.values.tolist()
#聚类和填充需要操作的列名
compute_header = ['charge_start_soc','charge_end_soc','charge_start_U','charge_end_U','charge_start_I','charge_end_I','charge_energy']
cluster_source = perfect_data[compute_header]
cluster_source_car = []
cluster_source_car.append(cluster_source[perfect_data['vehicle_id']==1])
cluster_source_car.append(cluster_source[perfect_data['vehicle_id']==2])
cluster_source_car.append(cluster_source[perfect_data['vehicle_id']==3])
cluster_source_car.append(cluster_source[perfect_data['vehicle_id']==4])
cluster_source_car.append(cluster_source[perfect_data['vehicle_id']==5])
cluster = []
labels = []
for source in cluster_source_car:
    kmeans = KMeans(n_clusters=5, random_state=0).fit(source[compute_header])
    cluster.append(kmeans.cluster_centers_)
    labels.append(kmeans.labels_)
cluster[0]

array([[ 36.42      ,  99.575     , 362.68875   , 398.1075    ,
         -8.3975    ,  -7.64125   ,  20.3935125 ],
       [ 63.72941176,  99.16470588, 370.43529412, 395.65294118,
        -20.6       ,  -8.92058824,  11.51367647],
       [ 26.06666667,  33.33333333, 371.65      , 389.28333333,
        -36.2       , -29.76666667,   5.739     ],
       [ 13.84      ,  37.92      , 362.1       , 395.67      ,
         -7.66      ,  -7.7       ,  19.5101    ],
       [ 52.56470588,  88.67058824, 370.05882353, 385.17941176,
        -29.47941176, -40.41176471,  11.50223529]])

In [6]:
def distance(vectorA=[], vectorB=[]):
    result = 0.0
    for i in range(len(vectorB)):
        x=vectorA[i]
        y=vectorB[i]
        if (not pd.isnull(y))and (y!=0.0):  
            result += (x-y)*(x-y)
    return np.sqrt(result)

In [7]:
def filling(vectorA=[], vectorB=[]):
    for i in range(len(vectorB)):
        x = vectorA[i]
        y = vectorB[i]
        if pd.isnull(y) or (y==0.0):
            vectorB[i] = x
    return vectorB

In [8]:
testA_car_result = []
compute_test_header = ['charge_start_soc','charge_end_soc','charge_start_U','charge_end_U','charge_start_I','charge_end_I']
for i in range(len(testA_car)):
    data_source = testA_car[i]
    tmp_data = data_source[compute_test_header]
    tmp_data = tmp_data.values
    for j in range(len(tmp_data)):
        maxD = float('inf')
        maxV = []
        data = tmp_data[j]
        for center in cluster[i]:
            dis = distance(center,data)
            if dis < maxD:
                maxD = dis
                maxV = center
        tmp_data[j] = filling(maxV,data)
    tmp_data = pd.DataFrame(tmp_data,columns=compute_test_header)
    for col in compute_test_header:
        for i in range(len(data_source[col])):
            data_source[col][i] = tmp_data[col][i]
    testA_car_result.append(data_source)
testA_car = testA_car_result
testA_car[2]

C:\Users\ytxlo\Anaconda3\lib\site-packages\ipykernel\__main__.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\ytxlo\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2963: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\ytxlo\Anaconda3\lib\site-packages\pandas\core\series.py:914: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.loc[key] = value


vehicle_id  charge_start_time  charge_end_time   mileage  \
7            3     20171201224526   20171201234816  142088.0   
8            3     20180123145343   20180123160544  150811.0   
9            3     20180304225122   20180305015229  155400.0   
10           3     20180519113736   20180519122556  169134.0   
11           3     20180610123152   20180610132701  172287.0   

    charge_start_soc  charge_end_soc  charge_start_U  charge_end_U  \
7                6.4            31.6           319.5         370.7   
8               11.2            34.4           330.5         371.5   
9               58.0            86.0           349.4         374.5   
10              82.0            90.0           365.6         372.6   
11              46.0            86.0           344.0         373.9   

    charge_start_I  charge_end_I  charge_max_temp  charge_min_temp  
7            -25.7         -16.2             27.0             10.0  
8            -84.2         -15.4             16.0              1.0  
9             -8.5          -7.9             14.0              6.0  
10            -8.1          -8.0             27.0             23.0  
11           -70.5         -16.3             34.0             24.0

In [9]:
import copy
header_v1=copy.deepcopy(header)  # 深拷贝
#header_v1.remove('vehicle_id')
header_v1.insert(4, 'delta_mileage')
for i in range(len(testA_car)):
    tmp_test = testA_car[i]
    tmp_data = dataset_car[i]
    tmp_test['uuid']=1
    tmp_data['uuid']=0
    tmp_data = tmp_data.append(tmp_test,sort=False)
    tmp_data.sort_values('mileage',inplace=True)
    mileage_list = tmp_data['mileage'].tolist()
    # 增加里程充电前汽车行驶里程数
    delta_mileage_list = [0] * len(mileage_list)
    for j in range(1, len(mileage_list)):
        delta_mileage = mileage_list[j] - mileage_list[j-1]
        delta_mileage_list[j] = delta_mileage
    tmp_data['delta_mileage'] = delta_mileage_list
    tmp_data = tmp_data[tmp_data['uuid']==1]
    testA_car[i] = tmp_data[header_v1]
testA_car[2]

C:\Users\ytxlo\Anaconda3\lib\site-packages\ipykernel\__main__.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\ytxlo\Anaconda3\lib\site-packages\ipykernel\__main__.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


vehicle_id  charge_start_time  charge_end_time   mileage  delta_mileage  \
7            3     20171201224526   20171201234816  142088.0           77.0   
8            3     20180123145343   20180123160544  150811.0           86.0   
9            3     20180304225122   20180305015229  155400.0           51.0   
10           3     20180519113736   20180519122556  169134.0            0.0   
11           3     20180610123152   20180610132701  172287.0          109.0   

    charge_start_soc  charge_end_soc  charge_start_U  charge_end_U  \
7                6.4            31.6           319.5         370.7   
8               11.2            34.4           330.5         371.5   
9               58.0            86.0           349.4         374.5   
10              82.0            90.0           365.6         372.6   
11              46.0            86.0           344.0         373.9   

    charge_start_I  charge_end_I  charge_max_temp  charge_min_temp  \
7            -25.7         -16.2             27.0             10.0   
8            -84.2         -15.4             16.0              1.0   
9             -8.5          -7.9             14.0              6.0   
10            -8.1          -8.0             27.0             23.0   
11           -70.5         -16.3             34.0             24.0   

    charge_energy  
7             NaN  
8             NaN  
9             NaN  
10            NaN  
11            NaN

In [10]:
import time
def str2time(string):
    year = string[0:4]
    month = string[4:6]
    day = string[6:8]
    hour = string[8:10]
    minute = string[10:12]
    second = string[12:14]
    time_str = '%s-%s-%s %s:%s:%s' % (year, month, day, hour, minute, second)
    timestamp = time.mktime(time.strptime(time_str, '%Y-%m-%d %H:%M:%S'))  # 变为时间戳
    return int(timestamp)

# 将矩阵内的字符串转化为时间戳
def calVecTimeStamp(vector):
    timestamps = []
    for v in vector:
        timestamp = str2time(str(v))
        timestamps.append(timestamp)
    return timestamps

In [11]:
header_v1.insert(3, 'charge_duration')
testA_car_r = []
for tmp_test in testA_car:
    testA_charge_end_time = np.array(calVecTimeStamp(tmp_test['charge_end_time']))
    testA_charge_start_time = np.array(calVecTimeStamp(tmp_test['charge_start_time']))
    tmp_test['charge_duration'] = (testA_charge_end_time - testA_charge_start_time).tolist()
    tmp_test = tmp_test[header_v1]
    testA_car_r.append(tmp_test)
testA_car = testA_car_r
testA_car[0]

vehicle_id  charge_start_time  charge_end_time  charge_duration  mileage  \
0           1     20171116161033   20171116170903             3510  71710.6   
1           1     20171210190533   20171210193743             1930  75816.9   
2           1     20180104213535   20180105042334            24479  79867.3   
3           1     20180215211935   20180216051456            28521  86867.6   

   delta_mileage  charge_start_soc  charge_end_soc  charge_start_U  \
0           59.8              44.0          90.800           370.5   
1          196.9              34.0          60.400           365.1   
2           75.5              39.2         100.000           364.0   
3          118.0              28.8          99.575           362.9   

   charge_end_U  charge_start_I  charge_end_I  charge_max_temp  \
0         383.9           -29.8         -40.1             21.0   
1         379.9           -25.9         -40.4             14.0   
2         399.9            -7.6          -7.8             11.0   
3         399.9            -7.6          -7.6              8.0   

   charge_min_temp  charge_energy  
0             13.0            NaN  
1              9.0            NaN  
2              2.0            NaN  
3              3.0            NaN

In [12]:
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.feature_selection import VarianceThreshold
from sklearn.linear_model import LinearRegression
preds = []
for i in range(0,5):
    no =i+1
    perfect_car_set = pd.read_csv(data_root + '/perfect_%d.csv'%no)
    header = perfect_car_set.columns.values.tolist()
    features = ['charge_duration', 'charge_start_soc', 'charge_start_U']
    X = perfect_car_set[header[3:14]]
    y = perfect_car_set[header[15]]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
    #标准化
    scaler = preprocessing.MinMaxScaler()
    X_train_scaled = scaler.fit_transform(X_train.astype(np.float64))
    #设置方差的阈值为0.08
    sel = VarianceThreshold(threshold=0.08)
    #选择方差大于0.08的特征
    X_sel=sel.fit_transform(X_train.astype(np.float64))
    linreg = LinearRegression()
    linreg.fit(X_train_scaled, y_train)
    test = testA_car[i]
    test = test[header_v1[3:14]]
    pred = linreg.predict(scaler.transform(test))
    preds.append(pred)
preds[0]

array([ 9.21738073,  9.19675257,  9.55602097, 11.39981107])

In [13]:
preds[1]

array([-10.08684396, -14.38939123, -17.29393528])

In [14]:
preds[2]

array([-66.94947979, -83.80831664, -65.92533392, -65.13708583,
       -80.85510338])

In [15]:
preds[3]

array([281.58437299, 295.26476179, 288.40656537, 291.61431417,
       278.15180652, 273.16098183, 282.58256295])

In [1]:
preds[4]

NameError: name 'preds' is not defined